### ISSUE TITLE
Does not compile vs. PostgreSQL's git master

### ISSUE THREAD

**Issue by davidfetter** [umitanuki/twitter_fdw#2]
The following patch fixes it:

diff --git a/twitter_fdw.c b/twitter_fdw.c
index 74f6a00..9f92851 100644
--- a/twitter_fdw.c
+++ b/twitter_fdw.c
@@ -15,6 +15,7 @@
 #include "parser/parsetree.h"
 #include "storage/fd.h"
 #include "utils/builtins.h"
+#include "utils/rel.h"

 #include "curl/curl.h"
 #include "libjson-0.8/json.h"

**Comment by umitanuki** [comment]
Fixed. Thanks for the report! I'll wrap it for PGXN later.
