### ISSUE TITLE
USE_PGXS is Deprecated

### ISSUE THREAD

**Issue by theory** [umitanuki/twitter_fdw#4]
The PostgreSQL hackers told me not to use it for any non-core extensions, and indeed, it is not mentioned in the [extension docs](http://www.postgresql.org/docs/current/static/extend-pgxs.html). The PGXN client doesn't set it, so some folks have had trouble installing twitter_fdw. So I suggest removing it, and just assuming that you're always using PGXS. Or add a NO_PGXS option if you really need a way to work around it, as I've done for [pgTAP](https://github.com/theory/pgtap/blob/master/Makefile#L14).

**Comment by umitanuki** [comment]
Right, and in fact I removed it from my kmeans module.  Will do it soon, with the FDW fix for 9.2 new API.

**Comment by theory** [comment]
Cool, thanks!

**Comment by umitanuki** [comment]
Yet I fixed USE_PGXS option only for now.  I need to look at FDW later.
